name: test

on:
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:3.6.22
        ports:
          - 27017:27017
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install backend
        run: npm install

      - name: npm install frontend
        run: npm install --prefix client

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          NODE_ENV: ${{secrets.NODE_ENV}}
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: npm run coverage
          coverageLocations: |
            ${{github.workspace}}/client/coverage/lcov.info:lcov
            ${{github.workspace}}/coverage/lcov.info:lcov
